spring.application.name=MPCT

# Server Port (Dynamic for Cloud)
server.port=${PORT}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
logging.level.org.springframework.security=INFO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# File Upload Configuration (Acepta archivos grandes para convertirlos a bytes)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT Secret (Secure string)
jwt.secret=${JWT_SECRET}

# Custom Application Properties
app.frontend.url=${APP_FRONTEND_URL}

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Mercado Pago (Producción)
mercadopago.access.token=${MERCADOPAGO_TOKEN}